name: CI

on:
  push:
    tags:
      - "v*.*.*"

env:
  NODE_VERSION: "18.19.0"
  NPM_ORG_NAMESPACE: "vela-ventures"
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: "https://registry.npmjs.org/"

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      - name: Publish
        run: npm publish
